### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by data-pup**
updates `gimli`, `fallible-iterator`, `csv`, and `regex` :slightly_smiling_face:

### CODE REVIEW

**Comment by data-pup** [comment]
a-ha! some of the tests were failing after updating the `csv` package. You can see the same sort of failure here: https://travis-ci.com/rustwasm/twiggy/jobs/205073544

Tracked this down to this commit in `csv`, which adds `ryu` and `itoa` as dependencies for the `csv` crate, to speed up float/integer serialization. Updated the tests cases to reflect that, you can see the same sort of changes happening upstream here:

https://github.com/BurntSushi/rust-csv/commit/6105a6adaff36f6af619a9e4156b2e83e7ebb956#diff-5e07616003d425b526178a965e987ce3L1304

**Comment by data-pup** [comment]
Once CI passes, we'll be able to close #263, #266, #280, #283, and #300. I wasn't having luck with updating `wasm-bindgen`, so that'll get taken care of later.

**Comment by fitzgen** [comment]
Thanks @data-pup!!

**Comment by data-pup** [comment]
No problem @fitzgen! I'd been wanting to take care of those as some point, happy it cleared up the dependabot backlog :slightly_smiling_face:

**Pull request merged**
